# Simple Food Blog Hugo Theme 

name = "Quiet Foodie"
license = "MIT"
licenselink = "https://github.com/paposeco/quietfoodie/LICENSE"
description = "Simple food blog with optional recipe schema markup"
homepage = "https://github.com/paposeco/quietfoodie/"
demosite = "https://paposeco.github.io/quietfoodie/"
tags = ["recipes", "blog"]
features = ["minimalist", "white"]

[author]
  name = "Fabi"
  homepage = "https://github.com/paposeco"
