# Minimal Hugo Theme 

name = "Minimal"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/LICENSE"
description = "Simple food blog"
homepage = "https://github.com/paposeco/cleanhugotheme"
demosite = "https://punchedpotatoes.com"
tags = ["recipes", "blog"]
features = ["minimalist", "white"]
min_version = "0.41.0"

[author]
  name = "Fabi"
  homepage = "https://github.com/paposeco"
